### ISSUE TITLE
delete tt_address from backend doesn't work??

### ISSUE THREAD

**Issue by zabinetta** [undkonsorten/registeraddress_logger#9]
Hi,
when the registeraddress_logger is installed in my installation, it is imposible to delete tt_address records from the backend. (TYPO3 8.7.18, tt_address 3.2.4, registeraddress_logger 1.0.3)
Is this behavior planned like this? I can understand, that this might be to get a complete history of an address-record, but if a Datenschutzbeauftragter needs to clear an address Record after a phonecall, its hard to handle.
with the best regards,
Sabine

**Comment by cumuru** [comment]
Hi @zabinetta,
there‘s no such feature I know of. A short poll among my colleagues wasn‘t successful either. So it might be a bug. 
Unfortunately, the developer who wrote most of the code is off for two more weeks.
Maybe you can provide some more detail so we can reproduce the issue? Missing information might include the version of `register_address`, the user account level (admin or not), and the steps taken (which of the many possibilities to delete records did you chose…).
Have you confirmed that the issue is introduced by and only by `register_address_logger` by enabling/disabling the extension?
Cheers,
Felix

**Comment by zabinetta** [comment]
Dear Felix,
I'm off for this week, too. Userlevel is: Admin. Registeraddress should be newest from ter . Steps taken: backend List Module, tried to delete tt_address Record. Then: Spinnengewebe Wheel of Death, nothing deleted.
But: can only verify the registeraddress version when i'm back. Best regards, Sabine 



Vom Handy gesendet

**Comment by msollmann** [comment]
I can confirm this behaviour. However, address records without associated logger records can be deleted as usual.

**Comment by arnekolja** [comment]
Can confirm this, too.
